### ISSUE TITLE
non works with functions!!

### ISSUE THREAD

**Issue by Arhimagistr** [sz-p/vscode-dependencyGraph#46]
As i think it's possible to work just with imports and requires but not with functions and so on. Anybody if you know let know me the tool which helps to debug JS code.. a lot of js code!!

..or may be some ideas how to setup dependencyGraph bind not only import and require but almost functions etc. ????

**Comment by sz-p** [comment]
Are you looking for [chrome devtools call-stack](https://developer.chrome.com/docs/devtools/javascript/reference/#call-stack)

![image](https://github.com/sz-p/vscode-dependencyGraph/assets/14040327/9bdefb78-fa71-4012-9f84-87e11058d1cb)

**Comment by Arhimagistr** [comment]
> Are you looking for [chrome devtools call-stack](https://developer.chrome.com/docs/devtools/javascript/reference/#call-stack)
> 
> ![image](https://user-images.githubusercontent.com/14040327/265565203-9bdefb78-fa71-4012-9f84-87e11058d1cb.png)

may be.. but like as dependencyGraph

**Comment by sz-p** [comment]
It is possible to find out who is calling this function in the call-stack, and it is consistent with the scenario of wanting to know which functions was called by this function and visualize to get dependencyGraph. However, the issue is beyond the scope of this extension, only the general scheme is provided here.

1. Get the AST of the function 

2. Parsing the AST to get the function call chain.

3. draw a visualization diagram

Finally, thank you very much for your support of this extension.
